
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: chatapp
  username: root
  password: hunter
  host: ddp

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
