
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: chatapp
  username: root
  password: password
  host: ddp
  socket: '/var/run/mysqld/mysqld.sock'

development:
  <<: *default

test:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: chatapp_test
  username: root
  password: password
  host: ddp_test
  socket: '/var/run/mysqld/mysqld.sock'

production:
  <<: *default
